import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = (props) => {
  

  return (
    <>
      <Head>
        <title>Prismagram</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>Prismagram</div>
    </>
  );
};

export default Home;


